apiVersion: v1
kind: ConfigMap
metadata:
  name: kitamoto-otomatik-user-service
data:
  KEYCLOAK_HOST:
  KEYCLOAK_TOKEN_CLIENT_ID_VALUE:
  KEYCLOAK_TOKEN_CLIENT_SECRET_VALUE:
  MAIL_HOST:
  ACCOUNT_ACTIVATION_URL:
  PASSWORD_RESET_URL:
  JWT_SECRET_KEY:
