apiVersion: v1
kind: Service
metadata:
  namespace: kitamoto-otomatik
  name: kitamoto-otomatik-user-service
  labels:
    app: kitamoto-otomatik-user-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9080
      targetPort: 8080
  selector:
    app: kitamoto-otomatik-user-service
